Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rawdatabt865
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
          

