Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rawdatabucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
          

